# Generated by Django 4.0.4 on 2022-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_customuser_avatar_customuser_name_customuser_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(default='-', max_length=50, verbose_name='login'),
        ),
    ]
