# Generated by Django 4.0.4 on 2022-05-18 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_good_amount_remove_good_images_good_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1, verbose_name='status')),
                ('price', models.IntegerField(default=1, verbose_name='price')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='phoneNumber')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=1, verbose_name='price')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderGoods', to='orders.order')),
            ],
        ),
    ]
