# Generated by Django 4.0.4 on 2022-05-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_good_amount_remove_good_images_good_images'),
        ('orders', '0002_alter_ordergoods_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderGoods',
            new_name='OrderGood',
        ),
    ]
