# Generated by Django 4.0.4 on 2022-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergood',
            name='adress',
            field=models.CharField(default='-', max_length=150, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='ordergood',
            name='delivery',
            field=models.CharField(default='-', max_length=50, verbose_name='delivery'),
        ),
    ]
