# Generated by Django 4.0.4 on 2022-05-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordergood_adress_ordergood_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergood',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='ordergood',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(default='-', max_length=150, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(default='-', max_length=50, verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='-', max_length=150, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='-', max_length=150, verbose_name='surname'),
        ),
    ]
