# Generated by Django 4.0.4 on 2022-05-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_ordergood_adress_remove_ordergood_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='-', max_length=150, verbose_name='address'),
        ),
    ]
