# Generated by Django 4.0.4 on 2022-07-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_goodimage_options_alter_good_description_and_more'),
        ('orders', '0009_order_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergood',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderGoods', to='goods.good'),
        ),
    ]
