# Generated by Django 4.0.4 on 2022-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('amount', models.IntegerField(default=0, verbose_name='price')),
                ('images', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.image')),
            ],
        ),
    ]
