# Generated by Django 4.0.4 on 2022-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
        migrations.RemoveField(
            model_name='good',
            name='images',
        ),
        migrations.AddField(
            model_name='good',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='goods', to='goods.image'),
        ),
    ]
