# Generated by Django 4.0.4 on 2022-06-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='price'),
        ),
    ]
